### ISSUE TITLE
Automated e2e checklist

### ISSUE THREAD

**Issue by ddeloy** [ddeloy/test-repo#12]
Write down a cross-component checklist for HAC (Appstore, Steam, mlops, DAI) and automate the testing, preferably using the API clients first, adding UI-driven automation later.

Checklist (needs input from @JHerna17):
* [ ] Login to HAC appstore
* [ ] Open My AI Engines link
  * [ ] steam UI should be displayed
  * [ ] user should be automatically logged to Steam
* [ ] Launch DAI instance with default (first in the list) profile and latest version, keeping all settings default
  * [ ] wait for instance to be running
  * [ ] open DAI instance
  * [ ] check the name of the logged DAI user
* [ ] Run a DAI experiment with default settings from /opt/h2oai/dai/sample_data/creditcard/creditcard.csv and 'default payment next month' as target column
* [ ] Create a project in DAI
* [ ] Link experiment to the project
* [ ] From Appstore UI open My Models
  * [ ] mlops UI should be displayed
  * [ ] user should be automatically logged to mlops
  * [ ] mlops should display a project with a model from previously finished experiment
  * [ ] deploy a model to DEV
  * [ ] check that the deployment is healthy
  * [ ] post data to deployed model endpoint to make a prediction
